export interface Talent {
  id: string;
  name: string;
  avatar: string;
  gender: 'Laki-laki' | 'Perempuan';
  age: number;
  location: string;
  education: 'SMA/SMK' | 'D3' | 'S1' | 'S2';
  title: string;
  expectedSalary: number;
  experienceYears: number;
  skills: string[];
  profileScore: number; // 0 - 100
  industry: string;
  jobCategory: string;
  jobInterest: string; // 'Full Time' | 'Part Time' | 'Contract'
  companyExperience: string[];
  // Persiapan Kerja
  readyNow: boolean;
  hasSim: boolean;
  hasSkck: boolean;
  hasCv: boolean;
  hasMotor: boolean;
  hasLaptop: boolean;
  hasCertificate: boolean;
  willingToRelocate: boolean;
}

export const mockTalents: Talent[] = [
  {
    id: 'talent-1',
    name: 'Budi Santoso',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', // using a quality headshot placeholder
    gender: 'Laki-laki',
    age: 27,
    location: 'Jakarta Selatan',
    education: 'S1',
    title: 'Frontend React Engineer',
    expectedSalary: 12000000,
    experienceYears: 4,
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Redux'],
    profileScore: 95,
    industry: 'Teknologi',
    jobCategory: 'IT & Software',
    jobInterest: 'Full Time',
    companyExperience: ['Tokopedia', 'Bukalapak'],
    readyNow: true,
    hasSim: true,
    hasSkck: true,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: false,
  },
  {
    id: 'talent-2',
    name: 'Siti Rahmawati',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    gender: 'Perempuan',
    age: 24,
    location: 'Bandung',
    education: 'D3',
    title: 'UI/UX Designer',
    expectedSalary: 8500000,
    experienceYears: 2,
    skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    profileScore: 88,
    industry: 'Kreatif',
    jobCategory: 'Design',
    jobInterest: 'Full Time',
    companyExperience: ['Gojek'],
    readyNow: true,
    hasSim: false,
    hasSkck: true,
    hasCv: true,
    hasMotor: false,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: true,
  },
  {
    id: 'talent-3',
    name: 'Rian Hidayat',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    gender: 'Laki-laki',
    age: 30,
    location: 'Surabaya',
    education: 'S1',
    title: 'Backend Developer',
    expectedSalary: 15000000,
    experienceYears: 6,
    skills: ['Node.js', 'Express', 'NestJS', 'PostgreSQL', 'Docker'],
    profileScore: 92,
    industry: 'Teknologi',
    jobCategory: 'IT & Software',
    jobInterest: 'Full Time',
    companyExperience: ['Shopee', 'Traveloka'],
    readyNow: false,
    hasSim: true,
    hasSkck: false,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: true,
  },
  {
    id: 'talent-4',
    name: 'Amalia Putri',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    gender: 'Perempuan',
    age: 22,
    location: 'Yogyakarta',
    education: 'S1',
    title: 'Digital Marketing Specialist',
    expectedSalary: 6000000,
    experienceYears: 1,
    skills: ['SEO', 'SEM', 'Social Media Ads', 'Copywriting'],
    profileScore: 85,
    industry: 'Marketing',
    jobCategory: 'Marketing',
    jobInterest: 'Contract',
    companyExperience: ['Ahensi Lokal'],
    readyNow: true,
    hasSim: true,
    hasSkck: true,
    hasCv: true,
    hasMotor: true,
    hasLaptop: false,
    hasCertificate: false,
    willingToRelocate: true,
  },
  {
    id: 'talent-5',
    name: 'Dimas Prabowo',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    gender: 'Laki-laki',
    age: 29,
    location: 'Tangerang',
    education: 'S1',
    title: 'Full Stack Engineer',
    expectedSalary: 18000000,
    experienceYears: 5,
    skills: ['React', 'Next.js', 'Node.js', 'MongoDB', 'AWS'],
    profileScore: 96,
    industry: 'Teknologi',
    jobCategory: 'IT & Software',
    jobInterest: 'Full Time',
    companyExperience: ['Kredivo', 'Dana'],
    readyNow: true,
    hasSim: true,
    hasSkck: true,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: false,
  },
  {
    id: 'talent-6',
    name: 'Dewi Lestari',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    gender: 'Perempuan',
    age: 25,
    location: 'Jakarta Barat',
    education: 'S1',
    title: 'Human Resources Specialist',
    expectedSalary: 9000000,
    experienceYears: 3,
    skills: ['Recruitment', 'Employee Relations', 'KPI Tracking', 'Training'],
    profileScore: 90,
    industry: 'Corporate Services',
    jobCategory: 'HR & Admin',
    jobInterest: 'Full Time',
    companyExperience: ['Sinarmas'],
    readyNow: true,
    hasSim: false,
    hasSkck: true,
    hasCv: true,
    hasMotor: false,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: false,
  },
  {
    id: 'talent-7',
    name: 'Kevin Wijaya',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    gender: 'Laki-laki',
    age: 26,
    location: 'Bekasi',
    education: 'SMA/SMK',
    title: 'Mobile App Developer',
    expectedSalary: 10000000,
    experienceYears: 2,
    skills: ['Flutter', 'Dart', 'Firebase', 'State Management'],
    profileScore: 89,
    industry: 'Teknologi',
    jobCategory: 'IT & Software',
    jobInterest: 'Contract',
    companyExperience: ['Framer Studio'],
    readyNow: true,
    hasSim: true,
    hasSkck: true,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: true,
  },
  {
    id: 'talent-8',
    name: 'Indah Kusuma',
    avatar: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150&auto=format&fit=crop&q=80',
    gender: 'Perempuan',
    age: 23,
    location: 'Depok',
    education: 'S1',
    title: 'Content Writer & SEO specialist',
    expectedSalary: 7000000,
    experienceYears: 1,
    skills: ['SEO Writing', 'WordPress', 'Google Analytics', 'Social Media'],
    profileScore: 84,
    industry: 'Media & Entertainment',
    jobCategory: 'Marketing',
    jobInterest: 'Part Time',
    companyExperience: ['IDN Times'],
    readyNow: true,
    hasSim: false,
    hasSkck: false,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: false,
    willingToRelocate: false,
  },
  {
    id: 'talent-9',
    name: 'Aditya Pratama',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    gender: 'Laki-laki',
    age: 28,
    location: 'Jakarta Pusat',
    education: 'S1',
    title: 'Product Manager',
    expectedSalary: 20000000,
    experienceYears: 4,
    skills: ['Product Roadmap', 'Agile/Scrum', 'Data Analysis', 'Jira'],
    profileScore: 93,
    industry: 'Teknologi',
    jobCategory: 'IT & Software',
    jobInterest: 'Full Time',
    companyExperience: ['OVO', 'Blibli'],
    readyNow: false,
    hasSim: true,
    hasSkck: true,
    hasCv: true,
    hasMotor: false,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: true,
  },
  {
    id: 'talent-10',
    name: 'Laras Rahayu',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    gender: 'Perempuan',
    age: 31,
    location: 'Surabaya',
    education: 'S2',
    title: 'Data Scientist',
    expectedSalary: 22000000,
    experienceYears: 7,
    skills: ['Python', 'SQL', 'Machine Learning', 'TensorFlow', 'Tableau'],
    profileScore: 97,
    industry: 'Finansial',
    jobCategory: 'IT & Software',
    jobInterest: 'Full Time',
    companyExperience: ['Bank Mandiri', 'Astra'],
    readyNow: true,
    hasSim: true,
    hasSkck: false,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: false,
  }
];

const names = ["Budi Santoso", "Siti Rahmawati", "Rian Hidayat", "Amalia Putri", "Dimas Prabowo", "Dewi Lestari", "Kevin Wijaya", "Indah Kusuma", "Aditya Pratama", "Laras Rahayu"];
const titles = ["Frontend React Engineer", "UI/UX Designer", "Backend Developer", "Digital Marketing Specialist", "Full Stack Engineer", "Human Resources Specialist", "Mobile App Developer", "Content Writer & SEO specialist", "Product Manager", "Data Scientist"];
const locations = ["Jakarta Selatan", "Bandung", "Surabaya", "Yogyakarta", "Tangerang", "Bekasi", "Depok", "Jakarta Pusat", "Jakarta Barat", "Semarang"];

const extraTalents: Talent[] = Array.from({ length: 110 }, (_, i) => {
  const idx = i % 10;
  const gender = idx % 2 === 0 ? 'Laki-laki' : 'Perempuan';
  const age = 22 + (i % 15);
  const education = (i % 4 === 0 ? 'S2' : i % 3 === 0 ? 'D3' : i % 2 === 0 ? 'SMA/SMK' : 'S1') as any;
  const name = `${names[idx]} ${i + 1}`;
  const title = titles[idx];
  const expectedSalary = 5000000 + (i * 500000) % 15000000;
  const experienceYears = 1 + (i % 8);
  const profileScore = 70 + (i % 28);
  return {
    id: `talent-${11 + i}`,
    name,
    avatar: `https://images.unsplash.com/photo-${1500000000000 + (i + 1) * 123456}?w=150&auto=format&fit=crop&q=80`,
    gender,
    age,
    location: locations[i % 10],
    education,
    title,
    expectedSalary,
    experienceYears,
    skills: ['React', 'Node.js', 'Figma', 'SEO', 'TypeScript'].slice(0, 1 + (i % 5)),
    profileScore,
    industry: 'Teknologi',
    jobCategory: 'IT & Software',
    jobInterest: 'Full Time',
    companyExperience: ['Tech Inc'],
    readyNow: true,
    hasSim: true,
    hasSkck: true,
    hasCv: true,
    hasMotor: true,
    hasLaptop: true,
    hasCertificate: true,
    willingToRelocate: true,
  };
});

mockTalents.push(...extraTalents);

